version: '3.8'
services:
  seagent:
    image: registry.cn-hangzhou.aliyuncs.com/nullskymc/seagent:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./vector_db:/app/vector_db
      - ./.env:/app/.env
    restart: unless-stopped
